### ISSUE TITLE
`pip install match` fails

### ISSUE THREAD

**Issue by amadanmath** [EducationalTestingService/match#24]
`pip install match==0.3.1` fails with the following message:

    Collecting match
      Downloading match-0.3.1.tar.gz (8.7 kB)
      Preparing metadata (setup.py) ... error
      error: subprocess-exited-with-error
      
      × python setup.py egg_info did not run successfully.
      │ exit code: 1
      ╰─> [8 lines of output]
          Traceback (most recent call last):
            File "<string>", line 2, in <module>
            File "<pip-setuptools-caller>", line 34, in <module>
            File "/private/var/folders/x8/vvr4pvdj00zcp80ml8s5ktt00000gn/T/pip-install-q5zjb7qi/match_7ef62f2438e64f7bb4b4dc2506b52d9e/setup.py", line 37, in <module>
              install_requires=requirements()
            File "/private/var/folders/x8/vvr4pvdj00zcp80ml8s5ktt00000gn/T/pip-install-q5zjb7qi/match_7ef62f2438e64f7bb4b4dc2506b52d9e/setup.py", line 12, in requirements
              with open('requirements.txt', 'r') as fh:
          FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
          [end of output]
      
      note: This error originates from a subprocess, and is likely not a problem with pip.
    error: metadata-generation-failed
    
    × Encountered error while generating package metadata.
    ╰─> See above for output.
    
    note: This is an issue with the package mentioned above, not pip.
    hint: See above for details.

However, installing directly from the repo works:

    pip install git+https://github.com/EducationalTestingService/match.git@v0.3.1

Tested on OSX Python 3.10.6

**Comment by tamarl08** [comment]
Thanks for reporting this. Fixed in version 0.3.2
